# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://jack-sparrow.github.io/
title: Jack Sparrow
email: jack-sparrow@gmail.com
author: Jack Sparrow
description: "Captain of the Pearl"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/jack-sparrow
  - icon: envelope-o
    title: email
    url: mailto:jack-sparrow@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/jack-sparrow/
  - icon: file-pdf-o
    title: CV
    url: img/CV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/jack-sparrow

