# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pablo-arantes.github.io/
title: Pablo R. Arantes
email: pablitoarantes@gmail.com
author: Pablo R. Arantes
description: "Research scientist at the University of California Riverside, working in the field of biophysics."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/pablo-arantes 
  - icon: envelope-o
    title: email
    url: mailto:pablitoarantes@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/pablo-ricardo-arantes/
  - icon: file-pdf-o
    title: CV
    url: img/CV_Arantes.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/pablitoarantes

