# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.MyName.com
title: Pablo R. Arantes
email: pablitoarantes@gmail.com
author: Pablo R. Aramtes
description: "Pablo Aramtes"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/pablo-arantes 
  - icon: envelope-o
    title: email
    url: mailto:pablitoarantes@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/pablo-ricardo-arantes/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/pablitoarantes

